Models/Producer.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.IO;

namespace Seller.Models
{
    public class Producer
    {
        [Key]
        public int ProducerId { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Site { get; set; }

        [Required(ErrorMessage = "Logo required")]
        public string LogoPath { get; set; }

        public string FullLogoPath
        {
            get
            {
                return String.Format("{0}Content{1}Images{1}Producers{1}{2}", AppDomain.CurrentDomain.BaseDirectory,
                                     Path.DirectorySeparatorChar, LogoPath);
            }
        }
    }
}

Controllers/ProducerController.cs
using System;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Seller.DAL;
using Seller.Models;
using Seller.Utils;

namespace Seller.Controllers
{
    public class ProducerController : Controller
    {
        private readonly DataContext db = new DataContext();

        //
        // GET: /Producer/
        [MultiAuthorize(Helper.Roles.Administrator, Helper.Roles.Moderator)]
        public ViewResult Index()
        {
            return View(db.Producers.ToList());
        }

        //
        // GET: /Producer/Details/5

        public ViewResult Details(int id)
        {
            Producer producer = db.Producers.Find(id);
            return View(producer);
        }

        //
        // GET: /Producer/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Producer/Create

        [HttpPost]
        [Authorize]
        public ActionResult Create(HttpPostedFileBase newImage, Producer producer, string submitButtons)
        {
            if (newImage != null)
            {
                String filePath = Guid.NewGuid() + Path.GetExtension(newImage.FileName);

                if (!string.IsNullOrWhiteSpace(producer.LogoPath))
                    System.IO.File.Delete(producer.FullLogoPath);

                producer.LogoPath = filePath;
                ModelState["LogoPath"].Errors.Clear();
                newImage.SaveAs(producer.FullLogoPath);
            }

            if (submitButtons == "Create")
            {
                if (ModelState.IsValid)
                {
                    db.Producers.Add(producer);
                    db.SaveChanges();
                    return RedirectAfterSuccess();
                }
            }

            return View(producer);
        }

        //
        // GET: /Producer/Edit/5
        [MultiAuthorize(Helper.Roles.Administrator, Helper.Roles.Moderator, Helper.Roles.TrustedShop)]
        public ActionResult Edit(int id)
        {
            Producer producer = db.Producers.Find(id);
            if (producer == null)
                return View("Error");

            return View(producer);
        }

        //
        // POST: /Producer/Edit/5

        [HttpPost]
        [MultiAuthorize(Helper.Roles.Administrator, Helper.Roles.Moderator, Helper.Roles.TrustedShop)]
        public ActionResult Edit(HttpPostedFileBase newImage, Producer producer, string submitButtons)
        {
            if (newImage != null)
            {
                String filePath = Guid.NewGuid() + Path.GetExtension(newImage.FileName);

                if (!string.IsNullOrWhiteSpace(producer.LogoPath))
                {
                    string prevValue =
                        db.Producers.Where(item => item.ProducerId == producer.ProducerId).Select(item => item.LogoPath)
                            .SingleOrDefault();
                    if (prevValue != producer.LogoPath)
                        System.IO.File.Delete(producer.FullLogoPath);
                }

                producer.LogoPath = filePath;
                newImage.SaveAs(producer.FullLogoPath);
            }

            if (submitButtons == "Save")
            {
                if (ModelState.IsValid)
                {
                    string prevValue =
                        db.Producers.Where(item => item.ProducerId == producer.ProducerId).Select(item => item.LogoPath)
                            .SingleOrDefault();
                    //remove old image
                    if (prevValue != producer.LogoPath)
                        System.IO.File.Delete(String.Format("{0}Content{1}Images{1}Producers{1}{2}",
                                                            AppDomain.CurrentDomain.BaseDirectory,
                                                            Path.DirectorySeparatorChar, prevValue));
                    db.Entry(producer).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectAfterSuccess();
                }
            }
            return View(producer);
        }

        //
        // GET: /Producer/Delete/5
        [MultiAuthorize(Helper.Roles.Administrator, Helper.Roles.Moderator)]
        public ActionResult Delete(int id)
        {
            Producer producer = db.Producers.Find(id);
            if (producer == null)
                return View("Error");
            ViewBag.CountUsed = db.Products.Count(item => item.ProducerId == id);
            return View(producer);
        }

        //
        // POST: /Producer/Delete/5

        [HttpPost, ActionName("Delete")]
        [MultiAuthorize(Helper.Roles.Administrator, Helper.Roles.Moderator)]
        public ActionResult DeleteConfirmed(int id)
        {
            Producer producer = db.Producers.Find(id);
            db.Producers.Remove(producer);
            db.SaveChanges();
            return RedirectAfterSuccess();
        }

        private ActionResult RedirectAfterSuccess()
        {
            if (Helper.Roles.ModeratorRoles.Any(role => User.IsInRole(role)))
                return RedirectToAction("Index");
            else
                return RedirectToAction("RedirectedBack", "Products");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/Producer/Create.cshtml
@using ViewRes
@model Seller.Models.Producer

@{
    ViewBag.Title = Localization.Create;
}

<h2>@Localization.Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"> </script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"> </script>

@using (Html.BeginForm("Create", "Producer", FormMethod.Post, new {enctype = "multipart/form-data"}))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>@Localization.Producer</legend>

        <div class="editor-label">
            @Localization.Name
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Localization.Site
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Site)
            @Html.ValidationMessageFor(model => model.Site)
        </div>
        @if (Model != null && !String.IsNullOrWhiteSpace(Model.LogoPath))
        {
            <img alt="@Localization.Logo" src="/Content/Images/Producers/@Model.LogoPath"/>
            <input id="LogoPath" name="LogoPath" type="hidden" value="@Model.LogoPath" />
        }
        @Html.ValidationMessageFor(model => model.LogoPath)
        
        <p>
            <input type="file" name="newImage"/>
            <button type="submit" name="submitButtons" value="Apply picture" class="cancel">@Localization.Apply_picture</button>
        </p>

        <p>
            <button type="submit" name="submitButtons" value="Create">@Localization.Create</button>
        </p>
    </fieldset>
}
    

<div>
    @Html.ActionLink(Localization.Back_to_producers, "Index", "Producer")
</div>

Views/Producer/Delete.cshtml
@using Seller.Utils
@using ViewRes
@model Seller.Models.Producer

@{
    ViewBag.Title = Localization.Delete;
}

<h2>@Localization.Delete</h2>

<h3>@Localization.SureDeleteProducer</h3>
<fieldset>
    <legend>@Localization.Producer</legend>

    @Localization.Name: @Html.DisplayFor(model => model.Name)<br/>
    @Localization.Site: @Html.DisplayFor(model => model.Site)<br/>
    @String.Format(Localization.used_count_times, ViewBag.CountUsed)
    <br/>
    <img alt="logo" src="/Content/Images/Producers/@Model.LogoPath"/>

</fieldset>
@using (Html.BeginForm())
{
    <p>
        @Html.HiddenFor(model => model.ProducerId)
        <input type="submit" value="@Localization.Delete" /> |
        @if (Helper.Roles.ModeratorRoles.Any(role => User.IsInRole(role)))
        {
            @Html.ActionLink(Localization.Back_to_producers, "Index")
            @:|
        }

        @Html.ActionLink(Localization.Back_to_products, "RedirectedBack", "Products")
    </p>
}

Views/Producer/Details.cshtml
@using Seller.Utils
@using ViewRes
@model Seller.Models.Producer

@{
    ViewBag.Title = Localization.Details;
}

<h2>@Localization.Details</h2>

<fieldset>
    <legend>Producer</legend>
    @Localization.Name: @Html.DisplayFor(model => model.Name)<br/>
    @Localization.Site: @Html.DisplayFor(model => model.Site)<br/>
    <br/>
    <img alt="logo" src="/Content/Images/Producers/@Model.LogoPath"/>
</fieldset>
<p>
    @if (Helper.Roles.TrustedRoles.Any(role => User.IsInRole(role)))
    {
        @Html.ActionLink(Localization.Edit, "Edit", new {id = Model.ProducerId})
        @: |
    }
    @if (Helper.Roles.ModeratorRoles.Any(role => User.IsInRole(role)))
    {
        @Html.ActionLink(Localization.Delete, "Delete", new {id = Model.ProducerId})
        @: |
    }

    @Html.ActionLink(Localization.Back_to_products, "RedirectedBack", "Products")
</p>

Views/Producer/Edit.cshtml
@using Seller.Utils
@using ViewRes
@model Seller.Models.Producer

@{
    ViewBag.Title = Localization.Edit;
}

<h2>@Localization.Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"> </script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"> </script>

@using (Html.BeginForm("Edit", "Producer", FormMethod.Post, new {enctype = "multipart/form-data"}))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>@Localization.Producer</legend>

        @Html.HiddenFor(model => model.ProducerId)

        <div class="editor-label">
            @Localization.Name
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Localization.Site
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Site)
            @Html.ValidationMessageFor(model => model.Site)
        </div>

        <img alt="@Localization.Logo" src="/Content/Images/Producers/@Model.LogoPath"/>
        <input id="LogoPath" name="LogoPath" type="hidden" value="@Model.LogoPath" />
        @Html.ValidationMessageFor(model => model.LogoPath)
        
        <p>
            <input type="file" name="newImage"/>
            <button type="submit" name="submitButtons" value="Apply picture">@Localization.Apply_picture</button>
        </p>

        <p>
            <button type="submit" name="submitButtons" value="Save">@Localization.Save</button>
        </p>
    </fieldset>
}

<div>
    @if (Helper.Roles.ModeratorRoles.Any(role => User.IsInRole(role)))
    {
        @Html.ActionLink(Localization.Back_to_index, "Index")
        @:|
    }

    @Html.ActionLink(Localization.Back_to_products, "RedirectedBack", "Products")
</div>

Views/Producer/Index.cshtml
@using Seller.Models
@using ViewRes
@model IEnumerable<Seller.Models.Producer>

@{
    ViewBag.Title = Localization.Index;
}

<h2>@Localization.Index</h2>

<p>
    @Html.ActionLink(Localization.Create_New, "Create") |
    @Html.ActionLink(Localization.Back_to_products, "RedirectedBack", "Products")
</p>
<table>
    <tr>
        <th>
            @Localization.Name
        </th>
        <th>
            @Localization.Site
        </th>
        <th>
            @Localization.Logo
        </th>
        <th></th>
    </tr>

    @foreach (Producer item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Site)
            </td>
            <td>
                <img alt="@Localization.Logo" class="gallery" src="/Content/Images/Producers/@item.LogoPath"/>
            </td>
            <td>
                @Html.ActionLink(Localization.Edit, "Edit", new {id = item.ProducerId}) |
                @Html.ActionLink(Localization.Delete, "Delete", new { id = item.ProducerId })
            </td>
        </tr>
    }

</table>