Controllers/OfferController.cs
using System;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using Seller.DAL;
using Seller.Models;
using Seller.Utils;

namespace Seller.Controllers
{
    [MultiAuthorize(Helper.Roles.Administrator, Helper.Roles.Moderator, Helper.Roles.TrustedShop, Helper.Roles.Shop)]
    public class OfferController : Controller
    {
        private readonly DataContext _db = new DataContext();

        [MultiAuthorize(Helper.Roles.Administrator, Helper.Roles.Moderator)]
        public ActionResult Index()
        {
            return
                View(_db.Offers.Include("Shop").Include("Product").OrderBy(offer => offer.ProductId)
                         .ThenBy(offer => offer.Price).ToList());
        }

        public ActionResult Create(int productId, int shopId)
        {
            return View(new Offer
                            {
                                ProductId = productId,
                                ShopId = shopId
                            });
        }

        [HttpPost]
        public ActionResult Create(Offer offer)
        {
            int curShopId = -1;
            if (Session[Helper.ShopId] != null)
                curShopId = (int) Session[Helper.ShopId];
            if (offer.ShopId == curShopId)
            {
                offer.LastUpdate = DateTime.Now;
                if (ModelState.IsValid)
                {
                    _db.Offers.Add(offer);
                    _db.SaveChanges();
                    return RedirectToAction("RedirectedBack", "Products");
                }
                return View(offer);
            }
            return View("Error");
        }


        public ActionResult Edit(int productId, int shopId)
        {
            Offer offer = _db.Offers.Find(productId, shopId);
            if (offer == null)
                offer = new Offer
                            {
                                ProductId = productId,
                                ShopId = shopId
                            };
            return View(offer);
        }

        [HttpPost]
        public ActionResult Edit(Offer offer)
        {
            int curShopId = -1;
            if (Session[Helper.ShopId] != null)
                curShopId = (int) Session[Helper.ShopId];
            if (offer.ShopId == curShopId)
            {
                offer.LastUpdate = DateTime.Now;
                if (ModelState.IsValid)
                {
                    _db.Entry(offer).State = EntityState.Modified;
                    _db.SaveChanges();
                    return RedirectToAction("RedirectedBack", "Products");
                }
                return View(offer);
            }
            return View("Error");
        }

        public ActionResult Delete(int productId, int shopId)
        {
            Offer removedOffer =
                _db.Offers.Include("Shop").Include("Product").SingleOrDefault(
                    offer => offer.ShopId == shopId && offer.ProductId == productId);
            if (removedOffer == null)
                return View("Error");
            return View(removedOffer);
        }

        [HttpPost, ActionName("Delete")]
        [MultiAuthorize(Helper.Roles.Administrator, Helper.Roles.Moderator)]
        public ActionResult DeleteConfirmed(Offer offer)
        {
            int curShopId = -1;
            if (Session[Helper.ShopId] != null)
                curShopId = (int) Session[Helper.ShopId];
            if (Helper.Roles.ModeratorRoles.Any(role => User.IsInRole(role)) || offer.ShopId == curShopId)
            {
                _db.Entry(offer).State = EntityState.Deleted;
                _db.SaveChanges();
                return RedirectToAction("RedirectedBack", "Products");
            }

            return View("Error");
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Controllers/ProductManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Seller.DAL;
using Seller.Models;
using Seller.Utils;

namespace Seller.Controllers
{
    [MultiAuthorize(Helper.Roles.Administrator, Helper.Roles.Moderator, Helper.Roles.TrustedShop, Helper.Roles.Shop)]
    public class ProductManagerController : Controller
    {
        private readonly DataContext _db = new DataContext();

        public ActionResult Create()
        {
            PrepareSelectLists();
            return View(new Product());
        }

        [HttpPost]
        public ActionResult Create(HttpPostedFileBase newImage, Product product, String submitButton)
        {
            switch (submitButton)
            {
                case "Add Picture":
                    AddPicture(newImage, product);
                    break;
                case "Create":
                    if (ModelState.IsValid)
                    {
                        product.EditedBy = product.CreatedBy = (Guid) Membership.GetUser().ProviderUserKey;
                        _db.Products.Add(product);
                        foreach (Image a in product.Images)
                        {
                            a.Product = product;
                            _db.Images.Add(a);
                        }
                        _db.SaveChanges();
                        return RedirectToAction("RedirectedBack", "Products");
                    }
                    break;
                default:
                    RemovePicture(product, submitButton);
                    break;
            }

            PrepareSelectLists();
            return View(product);
        }

        [MultiAuthorize(Helper.Roles.Administrator, Helper.Roles.Moderator, Helper.Roles.TrustedShop)]
        public ActionResult Edit(int id)
        {
            Product product = _db.Products.Include("Images").SingleOrDefault(model => model.ProductId == id);

            if (product == null)
                return View("Error");

            PrepareSelectLists(product.CategoryId, product.ProducerId);
            return View(product);
        }

        [HttpPost]
        [MultiAuthorize(Helper.Roles.Administrator, Helper.Roles.Moderator, Helper.Roles.TrustedShop)]
        public ActionResult Edit(HttpPostedFileBase newImage, Product product, String submitButton)
        {
            switch (submitButton)
            {
                case "Add Picture":
                    AddPicture(newImage, product);
                    break;
                case "Save":
                    if (ModelState.IsValid)
                    {
                        product.EditedBy = (Guid) Membership.GetUser().ProviderUserKey;
                        ICollection<Image> newImages = product.Images.ToList();
                        Dictionary<String, Image> oldImages =
                            _db.Images.Where(img => img.ProductId == product.ProductId).ToDictionary(image => image.Path);
                        foreach (Image a in newImages)
                        {
                            if (oldImages.ContainsKey(a.Path))
                            {
                                oldImages.Remove(a.Path);
                                product.Images.Remove(a);
                            }
                            else
                            {
                                a.Product = product;
                                _db.Images.Add(a);
                            }
                        }
                        foreach (Image a in oldImages.Values)
                        {
                            System.IO.File.Delete(a.FullPath);
                            _db.Images.Remove(a);
                        }

                        _db.Entry(product).State = EntityState.Modified;
                        _db.SaveChanges();
                        return RedirectToAction("RedirectedBack", "Products");
                    }
                    break;
                default:
                    RemovePicture(product, submitButton);
                    break;
            }

            PrepareSelectLists(product.CategoryId, product.ProducerId);
            return View(product);
        }

        [MultiAuthorize(Helper.Roles.Administrator, Helper.Roles.Moderator)]
        public ActionResult Delete(int id)
        {
            Product product =
                _db.Products.Include("Category").Include("Producer").Include("Images").SingleOrDefault(
                    item => item.ProductId == id);

            if (product == null)
                return View("Error");

            return View(product);
        }

        [HttpPost, ActionName("Delete")]
        [MultiAuthorize(Helper.Roles.Administrator, Helper.Roles.Moderator)]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = _db.Products.Include("Images").SingleOrDefault(item => item.ProductId == id);
            if (product == null)
                return View("Error");

            foreach(Image a in product.Images)
                System.IO.File.Delete(a.FullPath);
            _db.Products.Remove(product);
            _db.SaveChanges();
            return RedirectToAction("RedirectedBack", "Products");
        }

        [MultiAuthorize(Helper.Roles.Administrator, Helper.Roles.Moderator)]
        public ActionResult SetApproved(int id, bool approved)
        {
            if (ChangeApprovedState(id, approved))
            {
                return RedirectToAction("RedirectedBack", "Products");
            }
            else
            {
                return View("Error");
            }
        }

        [HttpPost]
        [MultiAuthorize(Helper.Roles.Administrator, Helper.Roles.Moderator)]
        public bool SetApproved(FormCollection formCollection, int id, bool approved)
        {
            return ChangeApprovedState(id, approved);
        }

        private bool ChangeApprovedState(int id, bool approved)
        {
            Product product = _db.Products.Find(id);
            if (product == null || product.Approved == approved)
                return false;
            product.Approved = approved;
            _db.SaveChanges();
            return true;
        }

        private static void AddPicture(HttpPostedFileBase newImage, Product product)
        {
            if (newImage != null)
            {
                String filePath = Guid.NewGuid() + Path.GetExtension(newImage.FileName);

                var newImg = new Image
                                 {
                                     ImageId = -1,
                                     Path = filePath
                                 };
                newImage.SaveAs(newImg.FullPath);
                product.Images.Add(newImg);
            }
        }

        private static void RemovePicture(Product product, string submitButton)
        {
            string path = submitButton.Substring(7); //remove "delete:"
            Image removedImage = product.Images.SingleOrDefault(img => img.Path == path);
            if (removedImage != null)
            {
                if (removedImage.ImageId < 1)
                    System.IO.File.Delete(removedImage.FullPath);
                product.Images.Remove(removedImage);
            }
        }

        private void PrepareSelectLists(int selectedCategoryId = -1, int selectedProducerId = -1)
        {
            ViewBag.CategoryId = PrepareCategorySelectList(_db.Categories.ToList(), selectedCategoryId);
            ViewBag.ProducerId = PrepareProducerSelectList(_db.Producers.ToList(), selectedProducerId);
        }

        private SelectList PrepareCategorySelectList(IEnumerable<Category> categoryList, int categoryId)
        {
            return new SelectList(categoryList, "CategoryId", "Name", categoryId);
        }

        private SelectList PrepareProducerSelectList(IEnumerable<Producer> producerList, int poducerId)
        {
            return new SelectList(producerList, "ProducerId", "Name", poducerId);
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Controllers/ProductsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using PagedList;
using Seller.DAL;
using Seller.Models;
using Seller.Utils;

namespace Seller.Controllers
{
    public class ProductsController : Controller
    {
        public const string SortOrderPrice = "Price";
        public const string SortOrderPriceDescending = "PriceDesc";
        public const string SortOrderName = "Name";
        public const string SortOrderNameDescending = "NameDesc";

        private readonly DataContext _db = new DataContext();

        public ActionResult RedirectedBack()
        {
            Dictionary<string, object> paramsDictionary = GetDictionary();
            return BuildIndex(GetParameter<int?>("category", paramsDictionary),
                              GetParameter<string>("sortOrder", paramsDictionary),
                              GetParameter<int?>("page", paramsDictionary),
                              GetParameter<int?>("pageSize", paramsDictionary),
                              GetParameter<string>("filter", paramsDictionary));
        }

        public ActionResult Index(int? category, string sortOrder, int? page, int? pageSize, string filter)
        {
            Dictionary<string, object> paramsDictionary = GetDictionary();

            paramsDictionary["filter"] = filter;
            paramsDictionary["category"] = category;
            paramsDictionary["sortOrder"] = sortOrder;
            paramsDictionary["page"] = page;
            paramsDictionary["pageSize"] = pageSize;

            return BuildIndex(category, sortOrder, page, pageSize, filter);
        }

        private ActionResult BuildIndex(int? category, string sortOrder, int? page, int? pageSize, string filter)
        {
            IQueryable<Product> query = from a in _db.Products.Include("Offers").Include("Category").Include("Producer")
                                        select a;
            if (!string.IsNullOrWhiteSpace(filter))
                query = query.Where(product => product.Name.ToUpper().Contains(filter.ToUpper()));
            if (!Roles.GetRolesForUser().Any(role => Helper.Roles.AllRoles.Contains(role)))
                query = query.Where(product => product.Approved);

            #region Category

            {
                List<Category> categoriesList = _db.Categories.ToList();

                foreach (Category a in categoriesList)
                {
                    if (a.CategoryId == category)
                    {
                        ViewBag.category = a.CategoryId;
                        query = query.Where(product => product.Category.CategoryId == a.CategoryId);
                        break;
                    }
                }

                ViewBag.Categories = new SelectList(categoriesList, "CategoryId", "Name");
            }

            #endregion

            #region Order

            ViewBag.filter = filter;
            ViewBag.NameOrder = SortOrderName;
            ViewBag.PriceOrder = SortOrderPrice;

            switch (sortOrder)
            {
                case SortOrderNameDescending:
                    query = query.OrderByDescending(a => a.Name);
                    ViewBag.Order = SortOrderNameDescending;
                    break;
                case SortOrderName:
                    query = query.OrderBy(a => a.Name);
                    ViewBag.NameOrder = SortOrderNameDescending;
                    ViewBag.Order = SortOrderName;
                    break;
                case SortOrderPriceDescending:
                    query = query.OrderByDescending(a => a.Offers.Min(offer => offer.Price));
                    ViewBag.Order = SortOrderPriceDescending;
                    break;
                default:
                    query = query.OrderBy(a => a.Offers.Min(offer => offer.Price));
                    ViewBag.PriceOrder = SortOrderPriceDescending;
                    ViewBag.Order = SortOrderPrice;
                    break;
            }

            #endregion

            ViewBag.isUserShop = Session["shopId"] != null;

            int productsPerPage = pageSize ?? 10;
            if (productsPerPage < 1) productsPerPage = int.MaxValue;

            bool isUserShop = Roles.GetRolesForUser().Any(role => Helper.Roles.ShopsRoles.Contains(role));
            ViewBag.isUserShop = isUserShop;

            return View("Index", query.ToPagedList(page ?? 1, productsPerPage));
        }

        public ActionResult BrowseProduct(int id)
        {
            Product product =
                (from a in _db.Products.Include("Offers.Shop").Include("Category").Include("Images").Include("Producer")
                 where a.ProductId == id
                 select a).SingleOrDefault();
            if (Request.RequestType.ToUpper() == "POST")
            {
                return PartialView(product);
            }
            else
            {
                return View(product);
            }
        }

        private Dictionary<string, object> GetDictionary()
        {
            Dictionary<string, object> paramsDictionary;
            if ((paramsDictionary = (Dictionary<string, object>) Session["requestParams"]) == null)
                Session["requestParams"] = paramsDictionary = new Dictionary<string, object>();
            return paramsDictionary;
        }

        private T GetParameter<T>(string paramName, Dictionary<string, object> dictionary)
        {
            object retValue;
            dictionary.TryGetValue(paramName, out retValue);
            return (T) retValue;
        }
    }
}

Views/Products/BrowseProduct.cshtml
@using System.Globalization
@using Seller.Models
@using ViewRes
@model Seller.Models.Product

@{
    ViewBag.Title = Model.Name;
}

<h2>@Model.Name</h2>
<p>@Localization.Type: @Model.Category.Name</p>
<p>@Localization.Producer: @Model.Producer.Name</p>
<p>@Model.Description</p>
@foreach (Image a in Model.Images)
{
    <img alt="@Localization.Image" src="/Content/Images/Products/@a.Path" class="gallery" />
}
<div class="clear">
    @if (Request.RequestType.ToUpper() == "GET")
    {
        <p><a href="/Products/RedirectedBack">@Localization.Back</a></p>
    }
    @if (Model.Offers.Count != 0)
    {
        foreach (Offer a in Model.Offers.OrderByDescending(offer => offer.LastUpdate))
        {
            <div class="maxWidth offerPanel">
                @{ int rub = a.Price*a.Shop.Exchange; }
                <span class="bold">@Localization.Price: @a.Price $, @rub rub</span><br/>
                <img alt="logo" src="/Content/Images/Shops/@a.Shop.Image"/>
                <div class="bold shop_name maxWidth">@a.Shop.Name</div>
                @if (!String.IsNullOrWhiteSpace(a.Shop.Phone))
                {
                    @Localization.Phone@:: @a.Shop.Phone<br/>
                }
                @if (!String.IsNullOrWhiteSpace(a.Shop.Site))
                {
                    @Localization.Site@:: @a.Shop.Site<br/>
                }
                @Localization.Email: @a.Shop.Email<br/>
                @if (!String.IsNullOrWhiteSpace(a.Shop.Adress))
                {
                    @Localization.Address@:: @a.Shop.Adress<br/>
                }
                @Localization.Last_update: @a.LastUpdate.ToString(CultureInfo.InvariantCulture)<br/><br/>
                <div class="maxWidth description">
                    @if (!String.IsNullOrWhiteSpace(a.Shop.Description))
                    {
                        @a.Shop.Description<br/>
                    }
                </div>
            </div>
        }
    }
    else
    {
        <p>@Localization.noOffers</p>
    }
</div>

Views/Products/Index.cshtml
@using System.Globalization
@using Seller.Controllers
@using Seller.Models
@using Seller.Utils
@using ViewRes
@model PagedList.IPagedList<Seller.Models.Product>
@{
    ViewBag.Title = Localization.Catalog;
    int shopId = -1;
    bool isUserModerator = Helper.Roles.ModeratorRoles.Any(role => User.IsInRole(role));
    bool isTrustedUser = isUserModerator || Helper.Roles.TrustedRoles.Any(role => User.IsInRole(role));
    if (Session[Helper.ShopId] != null)
    {
        shopId = (int) Session[Helper.ShopId];
    }
}

<h2>@Localization.Catalog</h2>

<script type="text/javascript" src="/Scripts/ajaxSetup.js"> </script>
<script type="text/javascript">
    var MOUSE_BUTTON_MIDDLE = 1;
    $(function () {
        $(".approve_link").click(function (e) {
            e = e || window.Event || window.event;
            if (e && e.button == MOUSE_BUTTON_MIDDLE) return true;
            var control = $(this);
            var url = this.href;
            $.post(this.href, function (result) {
                if (result == 'True') {
                    var state = (control.attr("text") == "@Localization.Approve");

                    control.attr("href", url.substring(0, url.lastIndexOf("=") + 1) + (!state));

                    control.html(state ? "@Localization.Disapprove" : "@Localization.Approve");

                    control.closest("tr").attr("class", state ? "approved" : "notApproved");
                }
            });
            return false;
        });
    });
</script>
<script type="text/javascript" src="/Scripts/browseProductAjax.js"> </script>

@using (Html.BeginForm("Index", "Products", FormMethod.Get, new {id = "indexForm"}))
{
    <input type="hidden" name="sortOrder" value="@ViewBag.Order"/>
    <input type="hidden" name="pageSize" value="@Model.PageSize"/>
    <input type="text" name="filter" value="@ViewBag.filter"/>
    @Html.DropDownList("category", (IEnumerable<SelectListItem>) ViewBag.categories, Localization.select_any,
                       new
                           {
                               onchange = "document.getElementById('indexForm').submit()"
                           })
    <noscript><input type="submit" value="@Localization.Filter" /></noscript>
    if (Helper.Roles.AllRoles.Any(role => User.IsInRole(role)))
    {
        <p>
            @Html.ActionLink(Localization.Create_New, "Create", "ProductManager")
        </p>
    }
    <table class="maxWidth">
        <thead>
            <tr>
                <th>@Html.ActionLink(Localization.Name, "Index", new {pageSize = Model.PageSize, ViewBag.category, sortOrder = ViewBag.NameOrder})
                    @if (ViewBag.Order == ProductsController.SortOrderName)
                    {
                        <img alt="asc" src="/Content/Images/Style/Asc.png"/>
                    }
                    else if (ViewBag.Order == ProductsController.SortOrderNameDescending)
                    {
                        <img alt="asc" src="/Content/Images/Style/Desc.png"/>
                    }
                </th>
                @if (ViewBag.category == null)
                {
                    <th>@Localization.Category</th>
                }
                <th>@Localization.Producer</th>
                <th>@Localization.Description</th>
                <th>@Html.ActionLink(@Localization.Price, "Index", new {pageSize = Model.PageSize, ViewBag.category, sortOrder = ViewBag.Priceorder})
                    @if (ViewBag.Order == ProductsController.SortOrderPrice)
                    {
                        <img alt="asc" src="/Content/Images/Style/Asc.png"/>
                    }
                    else if (ViewBag.Order == ProductsController.SortOrderPriceDescending)
                    {
                        <img alt="asc" src="/Content/Images/Style/Desc.png"/>
                    }
                </th>
                @if (shopId != -1)
                {
                    <th>
                        @Localization.Offer
                    </th>
                }
                @if (isTrustedUser)
                {
                    <th>@Localization.Actions</th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (Product product in Model)
            {
                string approvedName = product.Approved ? "approved" : "notApproved";
                <tr class="@approvedName">
                    <td><a href="/Products/BrowseProduct?id=@product.ProductId" class="product_name" data-id="@product.ProductId">@product.Name</a></td>
                    @if (ViewBag.category == null)
                    {
                        <td>@product.Category.Name</td>
                    }
                    <td><a href="/Producer/Details/@product.ProducerId">@product.Producer.Name</a></td>
                    <td>@product.Description</td>
                    <td class="nowrap">
                        @if (product.Offers.Count > 0)
                        {
                            @product.Offers.Min(offer => offer.Price)
                            @:-
                            @product.Offers.Max(offer => offer.Price)
                        }
                    </td>
                    @if (shopId != -1)
                    {
                        <td>
                            @{
                                Offer off = product.Offers.SingleOrDefault(offer => offer.ShopId == shopId);
                                if (off != null)
                                {
                                    @Html.ActionLink(off.Price.ToString(CultureInfo.InvariantCulture), "Edit", "Offer", new {productId = product.ProductId, shopId}, null)
                                }
                                else
                                {
                                    @Html.ActionLink(Localization.NONE, "Create", "Offer", new {productId = product.ProductId, shopId}, null)
                                }
                            }
                        </td>
                    }
                    @if (isTrustedUser)
                    {
                        <td>
                            @if (isUserModerator)
                            {
                                string url = @String.Format("/ProductManager/SetApproved?id={0}&approved={1}", product.ProductId, !product.Approved);
                                <a class="approve_link" href="@url">@(product.Approved ? Localization.Disapprove : Localization.Approve)</a>
                                <br/>
                                <a href="/ProductManager/Edit?id=@product.ProductId">@Localization.Edit</a>
                                <br/>
                                <a href="/ProductManager/Delete?id=@product.ProductId">@Localization.Delete</a>
                            }
                            else
                            {
                                <a href="/ProductManager/Edit?id=@product.ProductId">@Localization.Edit</a>
                            }
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
    <!-- Paging -->
    <div>
        @Localization.Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
        @Localization.of @Model.PageCount
     
        @if (Model.HasPreviousPage)
        {
            @Html.ActionLink("<<", "Index", new {ViewBag.filter, ViewBag.category, page = 1, pageSize = Model.PageSize, sortOrder = ViewBag.Order})
            @Html.Raw(" ")
            @Html.ActionLink("< " + Localization.Previous, "Index", new {ViewBag.filter, ViewBag.category, page = Model.PageNumber - 1, pageSize = Model.PageSize, sortOrder = ViewBag.Order})
        }
        else
        {
            @Html.Raw("<< < ")
            @Localization.Previous
        }
     
        @if (Model.HasNextPage)
        {
            @Html.ActionLink(Localization.Next + " >", "Index", new {ViewBag.filter, ViewBag.category, page = Model.PageNumber + 1, pageSize = Model.PageSize, sortOrder = ViewBag.Order})
            @Html.Raw(" ")
            @Html.ActionLink(">>", "Index", new {ViewBag.filter, ViewBag.category, page = Model.PageCount, pageSize = Model.PageSize, sortOrder = ViewBag.Order})
        }
        else
        {
            @Localization.Next
            @Html.Raw(" > >>")
        }
    </div>
    <div>
        <p>@Localization.Products_per_page:
            @Html.ActionLink("5", "Index", new {pageSize = 5, ViewBag.category, sortOrder = ViewBag.Order})
            @Html.ActionLink("10", "Index", new {pageSize = 10, ViewBag.category, sortOrder = ViewBag.Order})
            @Html.ActionLink("20", "Index", new {pageSize = 20, ViewBag.category, sortOrder = ViewBag.Order})
            @Html.ActionLink("50", "Index", new {pageSize = 50, ViewBag.category, sortOrder = ViewBag.Order})
            @Html.ActionLink(Localization.All, "Index", new {pageSize = 0, ViewBag.category, sortOrder = ViewBag.Order})
        </p>
    </div>
}
<div id="productBrowse" />